### ISSUE TITLE
JSON not working with inline-relationship component

### ISSUE THREAD

**Issue by vFire** [64robots/nova-fields#131] opened 2019-10-12 10:16 UTC
JSON not working on resource with belongto relationship

**Comment by disitec** [comment] 2019-10-12 10:39
Can you provide a detailed description?

**Comment by vFire** [comment] 2019-10-12 10:43
>             JSON::make('Options', [
>                 Text::make('Namesdfs'),
>                 Boolean::make('Active'),
>                 Text::make('Description'),
>             ], 'options'),

This works fine.

>             BelongsTo::make('Module', 'module', 'ModuleManager\Resources\Vmodule')
>                 ->sortable(),
But with this relationship field,  Errors occured:

> {
>     "message": "Unresolvable dependency resolving [Parameter #1 [ <required> $fields ]] in class R64\\NovaFields\\JSON",
>     "exception": "Illuminate\\Contracts\\Container\\BindingResolutionException",
>     "file": "Z:\\laragon\\wwwroot\\nova\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php",
>     "line": 975,

**Comment by vFire** [comment] 2019-10-12 13:55
I know what the problem is, it is conflicted with the relationship-inline, another nova component. Not because of the belongto relationship.

**Comment by vFire** [comment] 2019-10-12 14:10
> $class = app($item['component'], $attrs);

this is the exact code in inline-relationship component where cause of the errors.

**Comment by disitec** [comment] 2019-10-21 19:20
I would need more time for looking into this issue. I'll be happy to review a PR if anyone figure it out. Thanks!

**Comment by disitec** [comment] 2019-12-13 11:59
Closing this as the issue is not directly related with the package. Happy to review PRs on that.

**Closed by disitec** 2019-12-13 11:59 UTC
