### ISSUE TITLE
Row Sorting

### ISSUE THREAD

**Issue by temp1029** [64robots/nova-fields#184] opened 2020-10-16 18:00 UTC
Any chance the row field could be sort-able in the future? Either a drag-and-drop or something like what is implemented here: https://github.com/michielkempen/nova-order-field would be amazing.

I know the row field is just JSON behind the scenes, but having a nice way to sort the fields via Nova UI would be helpful, even if using it later on required extra code.

**Comment by beliolfa** [comment] 2021-02-15 14:04
Duplicate of #22 We need time to implement feature requests. We are open to PR but we prioritize features that we actually use in our internal projects. Thanks!

**Closed by beliolfa** 2021-02-15 14:04 UTC
