### ISSUE TITLE
Nova 2.6.1: BelongsTo field throws a Vue warning: Invalid default value for prop "fillValues"

### ISSUE THREAD

**Issue by thinckx** [64robots/nova-fields#141] opened 2019-11-05 12:03 UTC
## Environment (& tested on):

* PHP 7.1, 7.2
* Laravel 5.8, 6.x
* **Nova 2.6.1**
* nova-fields 0.12.0, 0.13.0

## Steps to reproduce

* Create User model + resource
* Create Post model + resource
* Create relationship `Post belongsTo User`
* Add field `R64\NovaFields\BelongsTo::make(__('User'), 'user', \App\Nova\User::class)`

### 2. `TypeError: "this.$refs.theEditor is undefined"` (with `quickCreate()`)

* Add `->quickCreate()` to `BelongsTo` field
* Try to add a model "on the fly"
* See error + popup flickering and errors continuously showing up

I guess these issue are caused by the latest Nova upgrades, or did I miss something? Could suggest what to do?

Thanks!

**Comment by disitec** [comment] 2019-11-08 15:04
Fixed in `0.14.0`. Thanks!

**Closed** 2019-11-08 15:03 UTC

**Comment by thinckx** [comment] 2019-11-08 15:47
Thanks for the update! The first error (warning) seems indeed fixed, but the second one still stands. Continuous errors when trying to `quickCreate()` a new resource.

**Comment by disitec** [comment] 2019-11-08 16:27
Sorry @thinckx I cant reproduce that issue in NOVA 2.6.1 nor 2.5.0. Have you tried to hard refresh your browser?

**Comment by thinckx** [comment] 2019-11-09 12:43
I have some feedback on this, would you prefer me to open a new issue?

**Comment by disitec** [comment] 2019-11-09 12:47
Yeah sure. That’s fine.
